In [1]:
!pip install -U git+https://github.com/huggingface/transformers.git git+https://github.com/huggingface/trl.git datasets bitsandbytes peft qwen-vl-utils wandb accelerate
# Tested with transformers==4.53.0.dev0, trl==0.20.0.dev0, datasets==3.6.0, bitsandbytes==0.46.0, peft==0.15.2, qwen-vl-utils==0.0.11, wandb==0.20.1, accelerate==1.8.1

Collecting git+https://github.com/huggingface/transformers.git
  Cloning https://github.com/huggingface/transformers.git to /tmp/pip-req-build-f_52j3xx
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-req-build-f_52j3xx
  Resolved https://github.com/huggingface/transformers.git to commit 21cb353b7b4f77c6f5f5c3341d660f86ff416d04
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/huggingface/trl.git
  Cloning https://github.com/huggingface/trl.git to /tmp/pip-req-build-c9558_87
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/trl.git /tmp/pip-req-build-c9558_87
  Resolved https://github.com/huggingface/trl.git to commit eef7a434270272f911600940166160156e80056b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: datasets in /home/student4/miniconda3/lib/python3.12/site-packages (3.6.0)
Requirement already satisfied: bitsandbytes in /home/student4/miniconda3/lib/python3.12/site-packages (0.46.0)
Requirement already satisfied: peft in /home/student4/miniconda3/lib/python3.12/site-packages (0.15.2)
Requirement already satisfied: qwen-vl-utils in /home/student4/miniconda3/lib/python3.12/site-packages (0.0.11)
Requirement already satisfied: wandb in /home/student4/miniconda3/lib/python3.12/site-packages (0.20.1)
Requirement already satisfied: accelerate in /home/student4/miniconda3/lib/python3.12/site-packages (1.8.1)
Requirement already satisfied: filelock in /home/student4/miniconda3/lib/python3.12/site-packages (from transformers==4.53.0.dev0) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from transformers==4.53.0.dev0) (0.31.2)
Requirement already satisfied: numpy>=1.17 in /home/student4/miniconda3/lib/python3.12/site-packages (from transformers==4.53.0.dev0) (2.3.0)
Requirement already satisfied: packaging>=20.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from transformers==4.53.0.dev0) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /home/student4/miniconda3/lib/python3.12/site-packages (from transformers==4.53.0.dev0) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /home/student4/miniconda3/lib/python3.12/site-packages (from transformers==4.53.0.dev0) (2024.11.6)
Requirement already satisfied: requests in /home/student4/miniconda3/lib/python3.12/site-packages (from transformers==4.53.0.dev0) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /home/student4/miniconda3/lib/python3.12/site-packages (from transformers==4.53.0.dev0) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /home/student4/miniconda3/lib/python3.12/site-packages (from transformers==4.53.0.dev0) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /home/student4/miniconda3/lib/python3.12/site-packages (from transformers==4.53.0.dev0) (4.66.5)
Requirement already satisfied: fsspec>=2023.5.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.53.0.dev0) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/student4/miniconda3/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.53.0.dev0) (4.14.0)
Requirement already satisfied: pyarrow>=15.0.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from datasets) (20.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /home/student4/miniconda3/lib/python3.12/site-packages (from datasets) (2.3.0)
Requirement already satisfied: xxhash in /home/student4/miniconda3/lib/python3.12/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /home/student4/miniconda3/lib/python3.12/site-packages (from datasets) (0.70.16)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/student4/miniconda3/lib/python3.12/site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.12.13)
Requirement already satisfied: torch<3,>=2.2 in /home/student4/miniconda3/lib/python3.12/site-packages (from bitsandbytes) (2.5.1+cu121)
Requirement already satisfied: networkx in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (3.3)
Requirement already satisfied: jinja2 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (3.1.0)
Requirement already satisfied: setuptools in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (78.1.1)
Requirement already satisfied: sympy==1.13.1 in /home/student4/miniconda3/lib/python3.12/site-packages (from torch<3,>=2.2->bitsandbytes) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/student4/miniconda3/lib/python3.12/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch<3,>=2.2->bitsandbytes) (12.1.105)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from sympy==1.13.1->torch<3,>=2.2->bitsandbytes) (1.3.0)
Requirement already satisfied: psutil in /home/student4/miniconda3/lib/python3.12/site-packages (from peft) (5.9.0)
Requirement already satisfied: av in /home/student4/miniconda3/lib/python3.12/site-packages (from qwen-vl-utils) (14.4.0)
Requirement already satisfied: pillow in /home/student4/miniconda3/lib/python3.12/site-packages (from qwen-vl-utils) (11.0.0)
Requirement already satisfied: click!=8.0.0,>=7.1 in /home/student4/miniconda3/lib/python3.12/site-packages (from wandb) (8.2.1)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from wandb) (3.1.44)
Requirement already satisfied: platformdirs in /home/student4/miniconda3/lib/python3.12/site-packages (from wandb) (4.3.7)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from wandb) (6.31.1)
Requirement already satisfied: pydantic<3 in /home/student4/miniconda3/lib/python3.12/site-packages (from wandb) (2.11.7)
Requirement already satisfied: sentry-sdk>=2.0.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from wandb) (2.30.0)
Requirement already satisfied: setproctitle in /home/student4/miniconda3/lib/python3.12/site-packages (from wandb) (1.3.6)
Requirement already satisfied: annotated-types>=0.6.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from pydantic<3->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /home/student4/miniconda3/lib/python3.12/site-packages (from pydantic<3->wandb) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from pydantic<3->wandb) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/student4/miniconda3/lib/python3.12/site-packages (from requests->transformers==4.53.0.dev0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/student4/miniconda3/lib/python3.12/site-packages (from requests->transformers==4.53.0.dev0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/student4/miniconda3/lib/python3.12/site-packages (from requests->transformers==4.53.0.dev0) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/student4/miniconda3/lib/python3.12/site-packages (from requests->transformers==4.53.0.dev0) (2025.6.15)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /home/student4/miniconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/student4/miniconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/student4/miniconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.5.0)
Requirement already satisfied: propcache>=0.2.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.20.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/student4/miniconda3/lib/python3.12/site-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/student4/miniconda3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /home/student4/miniconda3/lib/python3.12/site-packages (from jinja2->torch<3,>=2.2->bitsandbytes) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/student4/miniconda3/lib/python3.12/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/student4/miniconda3/lib/python3.12/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/student4/miniconda3/lib/python3.12/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /home/student4/miniconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
import gc
import time
import torch

def clear_memory():
    # Delete variables if they exist in the current global scope
    if "inputs" in globals():
        del globals()["inputs"]
    if "model" in globals():
        del globals()["model"]
    if "processor" in globals():
        del globals()["processor"]
    if "trainer" in globals():
        del globals()["trainer"]
    if "peft_model" in globals():
        del globals()["peft_model"]
    if "bnb_config" in globals():
        del globals()["bnb_config"]
    time.sleep(2)

    # Garbage collection and clearing CUDA memory
    gc.collect()
    time.sleep(1)
    torch.cuda.empty_cache()
    torch.cuda.synchronize()
    time.sleep(1)
    gc.collect()
    time.sleep(1)

    print(f"GPU allocated memory: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")
    print(f"GPU reserved memory: {torch.cuda.memory_reserved() / 1024**3:.2f} GB")

clear_memory()

GPU allocated memory: 0.00 GB
GPU reserved memory: 0.00 GB

In [3]:
system_message = """You are a Vision Language Model specialized in detecting clues of fire, smoke and surrounding context then classify them as no fire, dangerous fire or controlled fire.
Your task is to analyze the provided image and respond to queries with concise answers, usually a json format of a caption and a label.
Summarize what you see in the image. Describe the environment, key objects, people, and any signs of fire or smoke.
Based on your summary, classify the fire situation: no fire(e.g., fire alarm, fire distinguisher,..), controlled fire (e.g., fireplace emitting, campfire, cooking, candles, match stick, lighter..) or a dangerous/uncontrolled fire (e.g., curtains on fire, smoke on ceiling, couch on fire, bed sheet on fire, spreading fire on furniture..)
Focus on delivering accurate, succinct caption and precise label based on the visual information. Add a brief explanation for your choice of label in the caption if necessary."""

user_query = """Summarize this situation in the image, look for signs of fire and smoke and classify whether the situation is 
no fire(e.g., fire alarm, fire distinguisher,..), 
controlled fire (e.g., fireplace emitting, campfire, cooking, candles, match stick, lighter..) 
or a dangerous/uncontrolled fire (e.g., curtains on fire, smoke on ceiling, couch on fire, bed sheet on fire, spreading fire on furniture..)
Add a brief explanation for your choice of label in the caption if necessary.
Respond only this json format:
{ \"caption\": \"...\", \"label\": \"no fire\"|\"controlled fire\"|\"dangerous fire\" }
"""

In [4]:
from PIL import Image
import json

def format_data(sample):
    return [
        {
            "role": "system",
            "content": [{"type": "text", "text": system_message}],
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "image": Image.open(sample["image_path"]).convert("RGB"),
                },
                {
                    "type": "text",
                    "text": user_query,
                },
            ],
        },
        {
            "role": "assistant",
            "content": [
                {
                    "type": "text",
                    "text": f"""```json\n{json.dumps({"caption": sample["caption"], "label": sample["label"]}, ensure_ascii=False)}\n```"""
                }
            ],
        },
    ]

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load the dataset
df = pd.read_csv("labels_v2.csv")

# First split: separate out the test set (20%)
train_val_df, test_df = train_test_split(df, test_size=0.2, random_state=42, shuffle=True)

# Second split: split the remaining 80% into 70% train and 10% val
train_df, val_df = train_test_split(train_val_df, test_size=0.125, random_state=42, shuffle=True)
# 0.125 * 80% = 10% of total → val

# Print sizes
print(f"Train size: {len(train_df)}, Val size: {len(val_df)}, Test size: {len(test_df)}")

Train size: 322, Val size: 46, Test size: 93

In [6]:
train_df.head(10)

,image_path,label,caption
275,dataset_v2/image276.jpg,no fire,The image depicts a well-decorated dining room...
341,dataset_v2/image1304.jpg,dangerous fire,The image shows a vehicle engulfed in flames w...
24,dataset_v2/image25.jpg,no fire,"The image shows a modern, minimalist office sp..."
26,dataset_v2/image27.jpg,no fire,The image shows an empty office space with cub...
4,dataset_v2/image5.jpg,no fire,The image shows a hospital room with a patient...
413,dataset_v2/image1379.jpg,dangerous fire,A laptop on a wooden desk is on fire with flam...
350,dataset_v2/image1315.jpg,no fire,The image depicts a painting of a campfire wit...
80,dataset_v2/image81.jpg,no fire,The image shows an office setting with two des...
281,dataset_v2/image282.jpg,no fire,"The image shows a well-lit, organized workspac..."
160,dataset_v2/image161.jpg,no fire,The image shows a modern living room with a fi...

In [7]:
train_dataset = [format_data(sample) for sample in train_df.to_dict('records')]
eval_dataset = [format_data(sample) for sample in val_df.to_dict('records')]
test_dataset = [format_data(sample) for sample in test_df.to_dict('records')]

In [ ]:
import torch
from transformers import Qwen2_5_VLForConditionalGeneration, Qwen2_5_VLProcessor, BitsAndBytesConfig

model_id = "Qwen/Qwen2.5-VL-3B-Instruct"
# BitsAndBytesConfig int-4 config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True, bnb_4bit_use_double_quant=True, bnb_4bit_quant_type="nf4", bnb_4bit_compute_dtype=torch.bfloat16
)

model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    # quantization_config=bnb_config
)

processor = Qwen2_5_VLProcessor.from_pretrained(model_id, use_fast=True)

print("Successfully loaded the model")

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
You have video processor config saved in `preprocessor.json` file which is deprecated. Video processor configs should be saved in their own `video_preprocessor.json` file. You can rename the file or load and save the processor back which renames it automatically. Loading from `preprocessor.json` will be removed in v5.0.

Successfully loaded the model

In [10]:
from qwen_vl_utils import process_vision_info

def generate_text_from_sample(model, processor, sample, max_new_tokens=1024, device="cuda"):
    # Apply full chat template including system message
    text_input = processor.apply_chat_template(
        sample, tokenize=False, add_generation_prompt=True
    )

    # Process the visual input
    image_inputs, _ = process_vision_info(sample)

    # Prepare model inputs
    model_inputs = processor(
        text=[text_input],
        images=image_inputs,
        return_tensors="pt",
    ).to(device)

    # Generate response
    generated_ids = model.generate(**model_inputs, max_new_tokens=max_new_tokens)

    # Trim input tokens from generated output
    trimmed_generated_ids = [out_ids[len(in_ids):] for in_ids, out_ids in zip(model_inputs.input_ids, generated_ids)]

    # Decode to string
    output_text = processor.batch_decode(
        trimmed_generated_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False
    )

    return output_text[0]

In [11]:
from peft import LoraConfig, get_peft_model

# Configure LoRA
peft_config = LoraConfig(
    lora_alpha=16,
    lora_dropout=0.05,
    r=8,
    bias="none",
    target_modules=["q_proj", "v_proj"],
    task_type="CAUSAL_LM",
)

# Apply PEFT model adaptation
peft_model = get_peft_model(model, peft_config)

# Print trainable parameters
peft_model.print_trainable_parameters()

trainable params: 1,843,200 || all params: 3,756,466,176 || trainable%: 0.0491

In [12]:
from trl import SFTConfig

# Configure training arguments
training_args = SFTConfig(
    output_dir="qwen2-7b-instruct-trl-sft-ChartQA",  # Directory to save the model
    num_train_epochs=3,  # Number of training epochs
    per_device_train_batch_size=1,  # Batch size for training
    per_device_eval_batch_size=1,  # Batch size for evaluation
    gradient_accumulation_steps=2,  # Steps to accumulate gradients
    gradient_checkpointing=True,  # Enable gradient checkpointing for memory efficiency
    # Optimizer and scheduler settings
    optim="adamw_torch_fused",  # Optimizer type
    learning_rate=2e-4,  # Learning rate for training
    lr_scheduler_type="constant",  # Type of learning rate scheduler
    # Logging and evaluation
    logging_steps=10,  # Steps interval for logging
    eval_steps=10,  # Steps interval for evaluation
    eval_strategy="steps",  # Strategy for evaluation
    save_strategy="steps",  # Strategy for saving the model
    save_steps=20,  # Steps interval for saving
    metric_for_best_model="eval_loss",  # Metric to evaluate the best model
    greater_is_better=False,  # Whether higher metric values are better
    load_best_model_at_end=True,  # Load the best model after training
    # Mixed precision and gradient settings
    bf16=True,  # Use bfloat16 precision
    tf32=True,  # Use TensorFloat-32 precision
    max_grad_norm=0.3,  # Maximum norm for gradient clipping
    warmup_ratio=0.03,  # Ratio of total steps for warmup
    # Hub and reporting
    push_to_hub=True,  # Whether to push model to Hugging Face Hub
    report_to="wandb",  # Reporting tool for tracking metrics
    # Gradient checkpointing settings
    gradient_checkpointing_kwargs={"use_reentrant": True},  # Options for gradient checkpointing
    # Dataset configuration
    dataset_text_field="",  # Text field in dataset
    dataset_kwargs={"skip_prepare_dataset": True},  # Additional dataset options
    # max_seq_length=1024  # Maximum sequence length for input
)

training_args.remove_unused_columns = False  # Keep unused columns in dataset

In [13]:
import wandb

wandb.init(
    project="qwen2.5-3b-instruct-trl-sft-fire",
    name="qwen2.5-3b-instruct-trl-sft-fire",
    config=training_args,
)

wandb: Currently logged in as: minhduongqo (minhduongqo-university-of-science-and-technology-of-hano) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [14]:
# Create a data collator to encode text and image pairs
def collate_fn(examples):
    # Get the texts and images, and apply the chat template
    texts = [
        processor.apply_chat_template(example, tokenize=False) for example in examples
    ]  # Prepare texts for processing
    image_inputs = [process_vision_info(example)[0] for example in examples]  # Process the images to extract inputs

    # Tokenize the texts and process the images
    batch = processor(
        text=texts, images=image_inputs, return_tensors="pt", padding=True
    )  # Encode texts and images into tensors

    # The labels are the input_ids, and we mask the padding tokens in the loss computation
    labels = batch["input_ids"].clone()  # Clone input IDs for labels
    labels[labels == processor.tokenizer.pad_token_id] = -100  # Mask padding tokens in labels

    # Ignore the image token index in the loss computation (model specific)
    if isinstance(processor, Qwen2_5_VLProcessor):  # Check if the processor is Qwen2VLProcessor
        image_tokens = [151652, 151653, 151655]  # Specific image token IDs for Qwen2VLProcessor
    else:
        image_tokens = [processor.tokenizer.convert_tokens_to_ids(processor.image_token)]  # Convert image token to ID

    # Mask image token IDs in the labels
    for image_token_id in image_tokens:
        labels[labels == image_token_id] = -100  # Mask image token IDs in labels

    batch["labels"] = labels  # Add labels to the batch

    return batch  # Return the prepared batch

In [15]:
from trl import SFTTrainer
from torch import cuda

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    data_collator=collate_fn,
    peft_config=peft_config,
    processing_class=processor.tokenizer,
)

/home/student4/miniconda3/lib/python3.12/site-packages/peft/mapping_func.py:73: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/peft/tuners/tuners_utils.py:167: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

In [16]:
trainer.train()

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.

wandb: WARNING The get_url method is deprecated and will be removed in a future release. Please use `run.url` instead.
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/student4/miniconda3/lib/python3.12/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

TrainOutput(global_step=483, training_loss=0.522324070396137, metrics={'train_runtime': 2071.2042, 'train_samples_per_second': 0.466, 'train_steps_per_second': 0.233, 'total_flos': 1.967482688466125e+16, 'train_loss': 0.522324070396137})

In [17]:
trainer.save_model(training_args.output_dir)

Uploading...:   0%|          | 0.00/18.8M [00:00<?, ?B/s]